version: "3.7"
services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    image: backend
    container_name: booking_app
    env_file:
      - .env-non-dev
    command: bash -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 9000:8000
    depends_on:
      - db
      - redis
  
  celery:
    image: backend
    container_name: booking_celery
    command: bash -c "celery --app=app.tasks.celery_config:celery_app worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    image: backend
    container_name: booking_flower
    command: bash -c "celery -A app.tasks.celery_config:celery_app flower"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  